import type { Lead, TourPackage, Tour, HotelSupplier, Quotation, Payment } from "@/lib/types";

export const mockLeads: Lead[] = [
  {
    id: "1",
    name: "John & Sarah Mitchell",
    email: "john.mitchell@email.com",
    phone: "+44 7700 900123",
    source: "Client Portal",
    status: "quoted",
    destination: "Sri Lanka",
    travelDate: "2026-04-15",
    pax: 4,
    packageId: "p1",
    reference: "PCT-20260312-A3B7",
    notes: "Family trip, interested in cultural + wildlife",
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-10T14:30:00Z",
  },
  {
    id: "2",
    name: "Marie Dubois",
    email: "marie.d@outlook.fr",
    phone: "+33 6 12 34 56 78",
    source: "Client Portal",
    status: "contacted",
    destination: "Sri Lanka",
    travelDate: "2026-05-20",
    pax: 2,
    packageId: "p2",
    reference: "PCT-20260312-B4C8",
    notes: "Honeymoon, beach focus",
    createdAt: "2026-03-08T09:00:00Z",
    updatedAt: "2026-03-09T11:00:00Z",
  },
  {
    id: "3",
    name: "Zhang Wei",
    email: "zhang.wei@company.cn",
    phone: "+86 138 0000 1234",
    source: "Client Portal",
    status: "new",
    destination: "Sri Lanka",
    pax: 6,
    packageId: "p4",
    reference: "PCT-20260312-C5D9",
    notes: "Corporate retreat",
    createdAt: "2026-03-12T08:00:00Z",
    updatedAt: "2026-03-12T08:00:00Z",
  },
  {
    id: "4",
    name: "Emma Wilson",
    email: "emma.w@email.com",
    phone: "+1 555 123 4567",
    source: "Client Portal",
    status: "new",
    destination: "Sri Lanka",
    travelDate: "2026-06-10",
    pax: 2,
    packageId: "p2",
    reference: "PCT-20260312-X7K2",
    notes: "Beach & Culture Escape request",
    createdAt: "2026-03-12T10:00:00Z",
    updatedAt: "2026-03-12T10:00:00Z",
  },
  {
    id: "5",
    name: "Oliver Schmidt",
    email: "oliver.s@gmx.de",
    phone: "+49 170 987 6543",
    source: "Client Portal",
    status: "negotiating",
    destination: "Sri Lanka",
    travelDate: "2026-07-15",
    pax: 3,
    packageId: "p3",
    reference: "PCT-20260312-E7G1",
    notes: "Adventure seekers, want trekking + wildlife",
    createdAt: "2026-03-11T14:00:00Z",
    updatedAt: "2026-03-12T09:00:00Z",
  },
];

export const mockPackages: TourPackage[] = [
  {
    id: "p1",
    name: "Ceylon Heritage & Wildlife",
    duration: "8 Days / 7 Nights",
    destination: "Sri Lanka",
    region: "Cultural Triangle",
    imageUrl: "https://images.unsplash.com/photo-1588668803695-82674663b423?w=800",
    price: 1890,
    rating: 4.9,
    reviewCount: 127,
    featured: true,
    published: true,
    cancellationPolicy: "Free cancellation up to 24 hours before",
    currency: "USD",
    description: "Experience the best of Sri Lanka: ancient cities, tea country, and wildlife safaris.",
    itinerary: [
      { day: 1, title: "Arrival - Colombo", description: "Airport pickup, transfer to Negombo.", accommodation: "Jetwing Lagoon" },
      { day: 2, title: "Sigiriya & Dambulla", description: "Lion Rock fortress, cave temples.", accommodation: "Heritance Kandalama" },
      { day: 3, title: "Sigiriya to Kandy", description: "Temple of the Tooth, cultural show.", accommodation: "Cinnamon Citadel" },
      { day: 4, title: "Tea Country", description: "Nuwara Eliya, tea factory tour.", accommodation: "Heritance Tea Factory" },
      { day: 5, title: "Yala Safari", description: "Full day safari in Yala National Park.", accommodation: "Cinnamon Wild" },
      { day: 6, title: "Galle Coast", description: "Galle Fort, beach time.", accommodation: "Fort Bazaar" },
      { day: 7, title: "Southern Coast", description: "Free day, optional activities.", accommodation: "Fort Bazaar" },
      { day: 8, title: "Departure", description: "Transfer to Colombo airport." },
    ],
    inclusions: ["All accommodation", "Meals as specified", "Private vehicle", "Safari jeep", "Entrance fees"],
    exclusions: ["International flights", "Travel insurance", "Personal expenses"],
    accommodationOptions: [
      { id: "acc1", label: "Jetwing Lagoon", price: 120, priceType: "per_night", supplierId: "h1", isDefault: true },
      { id: "acc2", label: "Heritance Kandalama", price: 185, priceType: "per_night", supplierId: "h2" },
      { id: "acc3", label: "Fort Bazaar", price: 95, priceType: "per_night", supplierId: "h3" },
    ],
    transportOptions: [
      { id: "tr1", label: "Private Car & Driver", price: 80, priceType: "per_day", supplierId: "ht1", isDefault: true },
      { id: "tr2", label: "Premium Van", price: 120, priceType: "per_day" },
      { id: "tr3", label: "Luxury Coach", price: 50, priceType: "per_person" },
    ],
    mealOptions: [
      { id: "m1", label: "BB (Breakfast)", price: 0, priceType: "total", isDefault: true },
      { id: "m2", label: "HB (Half Board)", price: 25, priceType: "per_person" },
      { id: "m3", label: "FB (Full Board)", price: 45, priceType: "per_person" },
      { id: "m4", label: "AI (All Inclusive)", price: 75, priceType: "per_person" },
    ],
    createdAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "p2",
    name: "Beach & Culture Escape",
    duration: "5 Days / 4 Nights",
    destination: "Sri Lanka",
    region: "Southern Coast",
    imageUrl: "https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=800",
    price: 690,
    rating: 4.7,
    reviewCount: 89,
    featured: true,
    published: true,
    cancellationPolicy: "Free cancellation up to 24 hours before",
    currency: "USD",
    description: "A relaxing blend of Galle heritage and Unawatuna beach.",
    itinerary: [
      { day: 1, title: "Arrival - Galle", description: "Transfer from airport, explore Galle Fort.", accommodation: "Fort Bazaar" },
      { day: 2, title: "Galle Fort", description: "Walking tour, lighthouse, boutiques.", accommodation: "Fort Bazaar" },
      { day: 3, title: "Unawatuna Beach", description: "Beach day, optional snorkeling.", accommodation: "Fort Bazaar" },
      { day: 4, title: "Free Day", description: "Spa, cooking class, or relaxation.", accommodation: "Fort Bazaar" },
      { day: 5, title: "Departure", description: "Transfer to airport." },
    ],
    inclusions: ["Accommodation", "Breakfast", "Airport transfers", "Fort walk"],
    exclusions: ["Lunch & dinner", "International flights", "Activities"],
    accommodationOptions: [
      { id: "acc4", label: "Fort Bazaar", price: 95, priceType: "per_night", supplierId: "h3", isDefault: true },
    ],
    transportOptions: [
      { id: "tr4", label: "Private Car & Driver", price: 60, priceType: "per_day", supplierId: "ht1", isDefault: true },
    ],
    mealOptions: [
      { id: "m5", label: "BB (Breakfast)", price: 0, priceType: "total", isDefault: true },
      { id: "m6", label: "HB (Half Board)", price: 20, priceType: "per_person" },
    ],
    createdAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "p3",
    name: "Tea Country & Hill Country",
    duration: "4 Days / 3 Nights",
    destination: "Sri Lanka",
    region: "Tea Country",
    imageUrl: "https://images.unsplash.com/photo-1569827156433-daf971e7d91a?w=800",
    price: 420,
    rating: 4.8,
    reviewCount: 56,
    featured: false,
    published: true,
    cancellationPolicy: "Free cancellation up to 48 hours before",
    currency: "USD",
    description: "Scenic train rides, tea plantations, and cool mountain air.",
    itinerary: [
      { day: 1, title: "Kandy to Ella", description: "Scenic train journey through tea country.", accommodation: "98 Acres" },
      { day: 2, title: "Ella Exploration", description: "Little Adam's Peak, Nine Arch Bridge.", accommodation: "98 Acres" },
      { day: 3, title: "Nuwara Eliya", description: "Tea factory, Gregory Lake.", accommodation: "Heritance Tea Factory" },
      { day: 4, title: "Departure", description: "Transfer to Colombo or airport." },
    ],
    inclusions: ["Accommodation", "Breakfast", "Train tickets", "Tea factory tour"],
    exclusions: ["Lunch & dinner", "Flights"],
    accommodationOptions: [
      { id: "acc5", label: "98 Acres", price: 150, priceType: "per_night", supplierId: "h4", isDefault: true },
      { id: "acc6", label: "Heritance Tea Factory", price: 200, priceType: "per_night", supplierId: "h5" },
    ],
    transportOptions: [
      { id: "tr5", label: "Private Car & Driver", price: 70, priceType: "per_day", supplierId: "ht1", isDefault: true },
      { id: "tr6", label: "Premium Van", price: 90, priceType: "per_day", supplierId: "ht2" },
    ],
    mealOptions: [
      { id: "m7", label: "BB (Breakfast)", price: 0, priceType: "total", isDefault: true },
      { id: "m8", label: "HB (Half Board)", price: 22, priceType: "per_person" },
    ],
    createdAt: "2026-01-20T00:00:00Z",
  },
  {
    id: "p4",
    name: "Wildlife Safari Adventure",
    duration: "3 Days / 2 Nights",
    destination: "Sri Lanka",
    region: "Yala",
    imageUrl: "https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800",
    price: 550,
    rating: 4.6,
    reviewCount: 43,
    featured: true,
    published: true,
    cancellationPolicy: "Free cancellation up to 24 hours before",
    currency: "USD",
    description: "Yala National Park safari and beach relaxation.",
    itinerary: [
      { day: 1, title: "Arrival - Yala", description: "Transfer to safari lodge.", accommodation: "Cinnamon Wild" },
      { day: 2, title: "Full Day Safari", description: "Yala National Park wildlife safari.", accommodation: "Cinnamon Wild" },
      { day: 3, title: "Departure", description: "Beach stop, transfer to airport." },
    ],
    inclusions: ["Accommodation", "Meals", "Safari jeep", "Park fees"],
    exclusions: ["Flights", "Tips"],
    accommodationOptions: [
      { id: "acc7", label: "Cinnamon Wild", price: 220, priceType: "per_night", supplierId: "h6", isDefault: true },
      { id: "acc8", label: "Jetwing Yala", price: 180, priceType: "per_night", supplierId: "h7" },
    ],
    transportOptions: [
      { id: "tr7", label: "Safari Jeep", price: 100, priceType: "per_day", supplierId: "ht4", isDefault: true },
      { id: "tr8", label: "Private Car & Driver", price: 75, priceType: "per_day", supplierId: "ht1" },
    ],
    mealOptions: [
      { id: "m9", label: "FB (Full Board)", price: 40, priceType: "per_person", isDefault: true },
      { id: "m10", label: "AI (All Inclusive)", price: 65, priceType: "per_person" },
    ],
    createdAt: "2026-01-22T00:00:00Z",
  },
  {
    id: "p5",
    name: "Colombo City & Coast",
    duration: "2 Days / 1 Night",
    destination: "Sri Lanka",
    region: "Colombo",
    imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    price: 180,
    rating: 4.5,
    reviewCount: 31,
    featured: false,
    published: true,
    cancellationPolicy: "Free cancellation up to 12 hours before",
    currency: "USD",
    description: "Quick city tour, temples, and beachside dinner.",
    itinerary: [
      { day: 1, title: "Colombo Tour", description: "Gangaramaya Temple, markets, Galle Face.", accommodation: "Shangri-La Colombo" },
      { day: 2, title: "Departure", description: "Airport transfer." },
    ],
    inclusions: ["Accommodation", "Breakfast", "City tour", "Airport transfer"],
    exclusions: ["Lunch & dinner", "Shopping"],
    accommodationOptions: [
      { id: "acc9", label: "Shangri-La Colombo", price: 250, priceType: "per_night", supplierId: "h8", isDefault: true },
      { id: "acc10", label: "Jetwing Lagoon", price: 120, priceType: "per_night", supplierId: "h1" },
    ],
    transportOptions: [
      { id: "tr9", label: "Private Car & Driver", price: 60, priceType: "per_day", supplierId: "ht1", isDefault: true },
      { id: "tr10", label: "Luxury Coach", price: 30, priceType: "per_person", supplierId: "ht3" },
    ],
    mealOptions: [
      { id: "m11", label: "BB (Breakfast)", price: 0, priceType: "total", isDefault: true },
      { id: "m12", label: "HB (Half Board)", price: 35, priceType: "per_person" },
    ],
    createdAt: "2026-01-25T00:00:00Z",
  },
];

export const mockHotels: HotelSupplier[] = [
  { id: "h1", name: "Jetwing Lagoon", type: "hotel", location: "Negombo", defaultPricePerNight: 120, currency: "USD", createdAt: "2026-01-01T00:00:00Z" },
  { id: "h2", name: "Heritance Kandalama", type: "hotel", location: "Dambulla", defaultPricePerNight: 185, currency: "USD", createdAt: "2026-01-01T00:00:00Z" },
  { id: "h3", name: "Fort Bazaar", type: "hotel", location: "Galle", defaultPricePerNight: 95, currency: "USD", createdAt: "2026-01-01T00:00:00Z" },
  { id: "h4", name: "98 Acres", type: "hotel", location: "Ella", defaultPricePerNight: 150, currency: "USD", createdAt: "2026-01-01T00:00:00Z" },
  { id: "h5", name: "Heritance Tea Factory", type: "hotel", location: "Nuwara Eliya", defaultPricePerNight: 200, currency: "USD", createdAt: "2026-01-01T00:00:00Z" },
  { id: "h6", name: "Cinnamon Wild", type: "hotel", location: "Yala", defaultPricePerNight: 220, currency: "USD", createdAt: "2026-01-01T00:00:00Z" },
  { id: "h7", name: "Jetwing Yala", type: "hotel", location: "Yala", defaultPricePerNight: 180, currency: "USD", createdAt: "2026-01-01T00:00:00Z" },
  { id: "h8", name: "Shangri-La Colombo", type: "hotel", location: "Colombo", defaultPricePerNight: 250, currency: "USD", createdAt: "2026-01-01T00:00:00Z" },
  { id: "ht1", name: "Private Car & Driver", type: "transport", defaultPricePerNight: 80, currency: "USD", createdAt: "2026-01-01T00:00:00Z" },
  { id: "ht2", name: "Premium Van", type: "transport", defaultPricePerNight: 120, currency: "USD", createdAt: "2026-01-01T00:00:00Z" },
  { id: "ht3", name: "Luxury Coach", type: "transport", defaultPricePerNight: 50, currency: "USD", createdAt: "2026-01-01T00:00:00Z" },
  { id: "ht4", name: "Safari Jeep", type: "transport", defaultPricePerNight: 100, currency: "USD", createdAt: "2026-01-01T00:00:00Z" },
  { id: "ht5", name: "Minivan", type: "transport", defaultPricePerNight: 65, currency: "USD", createdAt: "2026-01-01T00:00:00Z" },
];

export const mockStats = [
  { label: "Active Bookings", value: "12", change: 8, icon: "bookings" as const },
  { label: "Scheduled Tours", value: "7", change: 2, icon: "tours" as const },
  { label: "Revenue (MTD)", value: "$24.5k", change: 12, icon: "revenue" as const },
  { label: "Conversion Rate", value: "34%", change: -2, icon: "conversion" as const },
];

export const mockUpcomingTours = [
  { id: "t1", client: "John & Sarah Mitchell", destination: "Ceylon Heritage & Wildlife", date: "Apr 15, 2026", days: 8 },
  { id: "t2", client: "Marie Dubois", destination: "Beach & Culture Escape", date: "May 20, 2026", days: 5 },
  { id: "t3", client: "Oliver Schmidt", destination: "Tea Country & Hill Country", date: "Jul 15, 2026", days: 4 },
  { id: "t4", client: "Zhang Wei", destination: "Wildlife Safari Adventure", date: "Jun 10, 2026", days: 3 },
  { id: "t5", client: "Emma Wilson", destination: "Colombo City & Coast", date: "Jun 10, 2026", days: 2 },
];

export const mockRecentLeads = [
  { id: "5", name: "Oliver Schmidt", source: "Google", status: "negotiating" as const },
  { id: "4", name: "Emma Wilson", source: "Client Portal", status: "new" as const },
  { id: "3", name: "Zhang Wei", source: "Instagram", status: "new" as const },
  { id: "2", name: "Marie Dubois", source: "Referral", status: "contacted" as const },
  { id: "1", name: "John & Sarah Mitchell", source: "Website", status: "quoted" as const },
];

export const mockTours: Tour[] = [
  {
    id: "t1",
    packageId: "p1",
    packageName: "Ceylon Heritage & Wildlife",
    leadId: "1",
    clientName: "John & Sarah Mitchell",
    startDate: "2026-04-15",
    endDate: "2026-04-22",
    pax: 4,
    status: "scheduled",
    totalValue: 7560,
    currency: "USD",
  },
  {
    id: "t2",
    packageId: "p2",
    packageName: "Beach & Culture Escape",
    leadId: "2",
    clientName: "Marie Dubois",
    startDate: "2026-05-20",
    endDate: "2026-05-24",
    pax: 2,
    status: "confirmed",
    totalValue: 1380,
    currency: "USD",
  },
  {
    id: "t3",
    packageId: "p3",
    packageName: "Tea Country & Hill Country",
    leadId: "5",
    clientName: "Oliver Schmidt",
    startDate: "2026-07-15",
    endDate: "2026-07-18",
    pax: 3,
    status: "scheduled",
    totalValue: 1890,
    currency: "USD",
  },
  {
    id: "t4",
    packageId: "p4",
    packageName: "Wildlife Safari Adventure",
    leadId: "3",
    clientName: "Zhang Wei",
    startDate: "2026-06-10",
    endDate: "2026-06-12",
    pax: 6,
    status: "scheduled",
    totalValue: 4200,
    currency: "USD",
  },
  {
    id: "t5",
    packageId: "p5",
    packageName: "Colombo City & Coast",
    leadId: "4",
    clientName: "Emma Wilson",
    startDate: "2026-06-10",
    endDate: "2026-06-11",
    pax: 2,
    status: "confirmed",
    totalValue: 520,
    currency: "USD",
  },
];

export const mockQuotations: Quotation[] = [
  { id: "q1", leadId: "1", clientName: "John & Sarah Mitchell", packageId: "p1", packageName: "Ceylon Heritage & Wildlife", amount: 7560, currency: "USD", status: "sent", createdAt: "2026-03-05T10:00:00Z" },
  { id: "q2", leadId: "2", clientName: "Marie Dubois", packageId: "p2", packageName: "Beach & Culture Escape", amount: 1380, currency: "USD", status: "accepted", createdAt: "2026-03-09T14:00:00Z" },
  { id: "q3", leadId: "3", clientName: "Zhang Wei", packageId: "p4", packageName: "Wildlife Safari Adventure", amount: 4200, currency: "USD", status: "draft", createdAt: "2026-03-11T09:00:00Z" },
  { id: "q4", leadId: "4", clientName: "Emma Wilson", packageId: "p5", packageName: "Colombo City & Coast", amount: 520, currency: "USD", status: "sent", createdAt: "2026-03-12T11:00:00Z" },
  { id: "q5", leadId: "5", clientName: "Oliver Schmidt", packageId: "p3", packageName: "Tea Country & Hill Country", amount: 1890, currency: "USD", status: "sent", createdAt: "2026-03-12T15:00:00Z" },
];

export const mockPayments: Payment[] = [
  { id: "pay1", type: "incoming", amount: 1500, currency: "USD", description: "Deposit - John & Sarah Mitchell", clientName: "John & Sarah Mitchell", reference: "PCT-20260312-A3B7", status: "completed", date: "2026-03-08" },
  { id: "pay2", type: "incoming", amount: 1380, currency: "USD", description: "Full payment - Marie Dubois", clientName: "Marie Dubois", reference: "PCT-20260312-B4C8", status: "completed", date: "2026-03-15" },
  { id: "pay3", type: "outgoing", amount: 420, currency: "USD", description: "Supplier - Jetwing Lagoon", status: "completed", date: "2026-03-10" },
  { id: "pay4", type: "incoming", amount: 520, currency: "USD", description: "Emma Wilson - Colombo tour", clientName: "Emma Wilson", status: "pending", date: "2026-03-12" },
  { id: "pay5", type: "outgoing", amount: 180, currency: "USD", description: "Transport - Private Car", status: "completed", date: "2026-03-14" },
];
